/// Predefined market index constituents for the Market Screener.
/// Ticker symbols are Yahoo Finance format.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MarketIndex {
    pub id: String,
    pub name: String,
    pub region: String,
    pub ticker_count: usize,
    pub source: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MarketIndexTicker {
    pub symbol: String,
    pub name: String,
}

/// Finnhub symbol mapping for US indices
pub const FINNHUB_INDEX_MAP: &[(&str, &str)] = &[
    ("sp500", "^GSPC"),
    ("nasdaq100", "^NDX"),
    ("dowjones30", "^DJI"),
];

pub fn get_available_indices(has_finnhub_key: bool) -> Vec<MarketIndex> {
    let source_for = |id: &str| -> String {
        if has_finnhub_key && FINNHUB_INDEX_MAP.iter().any(|(idx, _)| *idx == id) {
            "finnhub".into()
        } else {
            "static".into()
        }
    };

    vec![
        MarketIndex { id: "dax40".into(), name: "DAX 40".into(), region: "DE".into(), ticker_count: DAX40.len(), source: "static".into() },
        MarketIndex { id: "eurostoxx50".into(), name: "EURO STOXX 50".into(), region: "EU".into(), ticker_count: EUROSTOXX50.len(), source: "static".into() },
        MarketIndex { id: "smi20".into(), name: "SMI 20".into(), region: "CH".into(), ticker_count: SMI20.len(), source: "static".into() },
        MarketIndex { id: "atx20".into(), name: "ATX 20".into(), region: "AT".into(), ticker_count: ATX20.len(), source: "static".into() },
        MarketIndex { id: "sp500".into(), name: "S&P 500".into(), region: "US".into(), ticker_count: SP500.len(), source: source_for("sp500") },
        MarketIndex { id: "nasdaq100".into(), name: "NASDAQ 100".into(), region: "US".into(), ticker_count: NASDAQ100.len(), source: source_for("nasdaq100") },
        MarketIndex { id: "dowjones30".into(), name: "Dow Jones 30".into(), region: "US".into(), ticker_count: DOWJONES30.len(), source: source_for("dowjones30") },
        MarketIndex { id: "ftse100".into(), name: "FTSE 100".into(), region: "GB".into(), ticker_count: FTSE100.len(), source: "static".into() },
    ]
}

pub fn get_index_tickers(index_id: &str) -> Option<Vec<MarketIndexTicker>> {
    let data: &[(&str, &str)] = match index_id {
        "dax40" => &DAX40,
        "eurostoxx50" => &EUROSTOXX50,
        "smi20" => &SMI20,
        "atx20" => &ATX20,
        "sp500" => &SP500,
        "nasdaq100" => &NASDAQ100,
        "dowjones30" => &DOWJONES30,
        "ftse100" => &FTSE100,
        _ => return None,
    };
    Some(
        data.iter()
            .map(|(sym, name)| MarketIndexTicker {
                symbol: sym.to_string(),
                name: name.to_string(),
            })
            .collect(),
    )
}

// ============================================================================
// DAX 40
// ============================================================================

const DAX40: [(&str, &str); 40] = [
    ("ADS.DE", "Adidas"),
    ("AIR.DE", "Airbus"),
    ("ALV.DE", "Allianz"),
    ("BAS.DE", "BASF"),
    ("BAYN.DE", "Bayer"),
    ("BEI.DE", "Beiersdorf"),
    ("BMW.DE", "BMW"),
    ("BNR.DE", "Brenntag"),
    ("CBK.DE", "Commerzbank"),
    ("CON.DE", "Continental"),
    ("1COV.DE", "Covestro"),
    ("DTG.DE", "Daimler Truck"),
    ("DBK.DE", "Deutsche Bank"),
    ("DB1.DE", "Deutsche Börse"),
    ("DHL.DE", "Deutsche Post DHL"),
    ("DTE.DE", "Deutsche Telekom"),
    ("EOAN.DE", "E.ON"),
    ("FRE.DE", "Fresenius"),
    ("HNR1.DE", "Hannover Rück"),
    ("HEI.DE", "HeidelbergCement"),
    ("HEN3.DE", "Henkel VZ"),
    ("IFX.DE", "Infineon"),
    ("MBG.DE", "Mercedes-Benz"),
    ("MRK.DE", "Merck KGaA"),
    ("MTX.DE", "MTU Aero Engines"),
    ("MUV2.DE", "Munich Re"),
    ("P911.DE", "Porsche AG"),
    ("PAH3.DE", "Porsche SE"),
    ("QIA.DE", "QIAGEN"),
    ("RHM.DE", "Rheinmetall"),
    ("RWE.DE", "RWE"),
    ("SAP.DE", "SAP"),
    ("SRT3.DE", "Sartorius VZ"),
    ("SIE.DE", "Siemens"),
    ("ENR.DE", "Siemens Energy"),
    ("SHL.DE", "Siemens Healthineers"),
    ("SY1.DE", "Symrise"),
    ("VOW3.DE", "Volkswagen VZ"),
    ("VNA.DE", "Vonovia"),
    ("ZAL.DE", "Zalando"),
];

// ============================================================================
// EURO STOXX 50
// ============================================================================

const EUROSTOXX50: [(&str, &str); 50] = [
    ("ABI.BR", "AB InBev"),
    ("ADS.DE", "Adidas"),
    ("AD.AS", "Ahold Delhaize"),
    ("AIR.DE", "Airbus"),
    ("ALV.DE", "Allianz"),
    ("AMS.DE", "AMUNDI"),
    ("ASML.AS", "ASML"),
    ("CS.PA", "AXA"),
    ("BAS.DE", "BASF"),
    ("BAYN.DE", "Bayer"),
    ("SAN.PA", "Sanofi"),
    ("BMW.DE", "BMW"),
    ("BNP.PA", "BNP Paribas"),
    ("CRG.IR", "CRH"),
    ("BN.PA", "Danone"),
    ("DB1.DE", "Deutsche Börse"),
    ("DTE.DE", "Deutsche Telekom"),
    ("EOAN.DE", "E.ON"),
    ("EL.PA", "EssilorLuxottica"),
    ("ERF.DE", "Eurofins Scientific"),
    ("ENI.MI", "ENI"),
    ("FLTR.IR", "Flutter Entertainment"),
    ("RMS.PA", "Hermès"),
    ("IBE.MC", "Iberdrola"),
    ("ITX.MC", "Inditex"),
    ("IFX.DE", "Infineon"),
    ("INGA.AS", "ING Group"),
    ("ISP.MI", "Intesa Sanpaolo"),
    ("KER.PA", "Kering"),
    ("OR.PA", "L'Oréal"),
    ("MC.PA", "LVMH"),
    ("MBG.DE", "Mercedes-Benz"),
    ("MUV2.DE", "Munich Re"),
    ("NOKIA.HE", "Nokia"),
    ("ORA.PA", "Orange"),
    ("PRX.AS", "Prosus"),
    ("SAF.PA", "Safran"),
    ("SAN.MC", "Santander"),
    ("SAP.DE", "SAP"),
    ("SU.PA", "Schneider Electric"),
    ("SIE.DE", "Siemens"),
    ("GLE.PA", "Société Générale"),
    ("STLAM.MI", "Stellantis"),
    ("TTE.PA", "TotalEnergies"),
    ("DG.PA", "Vinci"),
    ("VIV.PA", "Vivendi"),
    ("VOW3.DE", "Volkswagen VZ"),
    ("VNA.DE", "Vonovia"),
    ("AI.PA", "Air Liquide"),
    ("DSY.PA", "Dassault Systèmes"),
];

// ============================================================================
// SMI 20
// ============================================================================

const SMI20: [(&str, &str); 20] = [
    ("ABBN.SW", "ABB"),
    ("ADEN.SW", "Adecco"),
    ("GEBN.SW", "Geberit"),
    ("GIVN.SW", "Givaudan"),
    ("HOLN.SW", "Holcim"),
    ("KNIN.SW", "Kühne+Nagel"),
    ("LONN.SW", "Lonza"),
    ("NESN.SW", "Nestlé"),
    ("NOVN.SW", "Novartis"),
    ("PGHN.SW", "Partners Group"),
    ("ROG.SW", "Roche"),
    ("SREN.SW", "Swiss Re"),
    ("SCMN.SW", "Swisscom"),
    ("SLHN.SW", "Swiss Life"),
    ("SIKA.SW", "Sika"),
    ("UBSG.SW", "UBS"),
    ("ZURN.SW", "Zurich Insurance"),
    ("SGSN.SW", "SGS"),
    ("LOGN.SW", "Logitech"),
    ("SOON.SW", "Sonova"),
];

// ============================================================================
// ATX 20
// ============================================================================

const ATX20: [(&str, &str); 20] = [
    ("ANDR.VI", "Andritz"),
    ("ATS.VI", "AT&S"),
    ("BG.VI", "BAWAG Group"),
    ("CAI.VI", "CA Immo"),
    ("DO.VI", "DO & CO"),
    ("EBS.VI", "Erste Group"),
    ("EVN.VI", "EVN"),
    ("IIA.VI", "Immofinanz"),
    ("LNZ.VI", "Lenzing"),
    ("MARE.VI", "Mayr-Melnhof"),
    ("OMV.VI", "OMV"),
    ("POST.VI", "Österreichische Post"),
    ("RBI.VI", "Raiffeisen Bank Int."),
    ("SBO.VI", "Schoeller-Bleckmann"),
    ("SPI.VI", "Semperit"),
    ("TKA.VI", "Telekom Austria"),
    ("UQA.VI", "UNIQA Insurance"),
    ("VER.VI", "Verbund"),
    ("VIG.VI", "Vienna Insurance"),
    ("VOE.VI", "voestalpine"),
];

// ============================================================================
// Dow Jones 30
// ============================================================================

const DOWJONES30: [(&str, &str); 30] = [
    ("AAPL", "Apple"),
    ("AMGN", "Amgen"),
    ("AMZN", "Amazon"),
    ("AXP", "American Express"),
    ("BA", "Boeing"),
    ("CAT", "Caterpillar"),
    ("CRM", "Salesforce"),
    ("CSCO", "Cisco"),
    ("CVX", "Chevron"),
    ("DIS", "Walt Disney"),
    ("GS", "Goldman Sachs"),
    ("HD", "Home Depot"),
    ("HON", "Honeywell"),
    ("IBM", "IBM"),
    ("JNJ", "Johnson & Johnson"),
    ("JPM", "JPMorgan Chase"),
    ("KO", "Coca-Cola"),
    ("MCD", "McDonald's"),
    ("MMM", "3M"),
    ("MRK", "Merck & Co."),
    ("MSFT", "Microsoft"),
    ("NKE", "Nike"),
    ("NVDA", "NVIDIA"),
    ("PG", "Procter & Gamble"),
    ("SHW", "Sherwin-Williams"),
    ("TRV", "Travelers"),
    ("UNH", "UnitedHealth"),
    ("V", "Visa"),
    ("VZ", "Verizon"),
    ("WMT", "Walmart"),
];

// ============================================================================
// NASDAQ 100 (as of January 2026, after Dec 2025 reconstitution + WMT/AZN swap)
// ============================================================================

const NASDAQ100: [(&str, &str); 101] = [
    ("AAPL", "Apple"),
    ("ABNB", "Airbnb"),
    ("ADBE", "Adobe"),
    ("ADI", "Analog Devices"),
    ("ADP", "ADP"),
    ("ADSK", "Autodesk"),
    ("AEP", "American Electric Power"),
    ("ALNY", "Alnylam Pharmaceuticals"),
    ("AMAT", "Applied Materials"),
    ("AMD", "AMD"),
    ("AMGN", "Amgen"),
    ("AMZN", "Amazon"),
    ("ANSS", "ANSYS"),
    ("APP", "AppLovin"),
    ("ARM", "Arm Holdings"),
    ("ASML", "ASML"),
    ("AVGO", "Broadcom"),
    ("BKNG", "Booking Holdings"),
    ("BKR", "Baker Hughes"),
    ("CCEP", "Coca-Cola Europacific"),
    ("CDNS", "Cadence Design"),
    ("CEG", "Constellation Energy"),
    ("CHTR", "Charter Communications"),
    ("CMCSA", "Comcast"),
    ("COST", "Costco"),
    ("CPRT", "Copart"),
    ("CRWD", "CrowdStrike"),
    ("CSGP", "CoStar Group"),
    ("CSCO", "Cisco"),
    ("CTAS", "Cintas"),
    ("CTSH", "Cognizant"),
    ("DASH", "DoorDash"),
    ("DDOG", "Datadog"),
    ("DLTR", "Dollar Tree"),
    ("DXCM", "DexCom"),
    ("EA", "Electronic Arts"),
    ("EXC", "Exelon"),
    ("FANG", "Diamondback Energy"),
    ("FAST", "Fastenal"),
    ("FER", "Ferrovial"),
    ("FTNT", "Fortinet"),
    ("GEHC", "GE HealthCare"),
    ("GILD", "Gilead Sciences"),
    ("GOOG", "Alphabet A"),
    ("GOOGL", "Alphabet C"),
    ("HON", "Honeywell"),
    ("IDXX", "IDEXX Labs"),
    ("ILMN", "Illumina"),
    ("INSM", "Insmed"),
    ("INTC", "Intel"),
    ("INTU", "Intuit"),
    ("ISRG", "Intuitive Surgical"),
    ("KDP", "Keurig Dr Pepper"),
    ("KHC", "Kraft Heinz"),
    ("KLAC", "KLA Corp"),
    ("LIN", "Linde"),
    ("LRCX", "Lam Research"),
    ("MAR", "Marriott"),
    ("MCHP", "Microchip Technology"),
    ("MDB", "MongoDB"),
    ("MDLZ", "Mondelez"),
    ("MELI", "MercadoLibre"),
    ("META", "Meta Platforms"),
    ("MNST", "Monster Beverage"),
    ("MPWR", "Monolithic Power Systems"),
    ("MRNA", "Moderna"),
    ("MRVL", "Marvell Technology"),
    ("MSFT", "Microsoft"),
    ("MU", "Micron"),
    ("NFLX", "Netflix"),
    ("NVDA", "NVIDIA"),
    ("NXPI", "NXP Semiconductors"),
    ("ODFL", "Old Dominion Freight"),
    ("ORLY", "O'Reilly Auto"),
    ("PANW", "Palo Alto Networks"),
    ("PAYX", "Paychex"),
    ("PCAR", "PACCAR"),
    ("PDD", "PDD Holdings"),
    ("PEP", "PepsiCo"),
    ("PLTR", "Palantir"),
    ("PYPL", "PayPal"),
    ("QCOM", "Qualcomm"),
    ("REGN", "Regeneron"),
    ("ROP", "Roper Technologies"),
    ("ROST", "Ross Stores"),
    ("SBUX", "Starbucks"),
    ("SNPS", "Synopsys"),
    ("STX", "Seagate Technology"),
    ("TEAM", "Atlassian"),
    ("TMUS", "T-Mobile US"),
    ("TSLA", "Tesla"),
    ("TTWO", "Take-Two"),
    ("TXN", "Texas Instruments"),
    ("VRSK", "Verisk Analytics"),
    ("VRTX", "Vertex Pharmaceuticals"),
    ("WBD", "Warner Bros Discovery"),
    ("WDC", "Western Digital"),
    ("WDAY", "Workday"),
    ("WMT", "Walmart"),
    ("XEL", "Xcel Energy"),
    ("ZS", "Zscaler"),
];

// ============================================================================
// FTSE 100 (as of March 2026 quarterly review: +IGG, +LION, -EZJ, -HIK)
// ============================================================================

const FTSE100: [(&str, &str); 100] = [
    ("AAL.L", "Anglo American"),
    ("ABF.L", "Associated British Foods"),
    ("ADM.L", "Admiral Group"),
    ("AHT.L", "Ashtead Group"),
    ("ANTO.L", "Antofagasta"),
    ("AUTO.L", "Auto Trader"),
    ("AV.L", "Aviva"),
    ("AZN.L", "AstraZeneca"),
    ("BA.L", "BAE Systems"),
    ("BARC.L", "Barclays"),
    ("BDEV.L", "Barratt Developments"),
    ("BKG.L", "Berkeley Group"),
    ("BME.L", "B&M European"),
    ("BNZL.L", "Bunzl"),
    ("BP.L", "BP"),
    ("BRBY.L", "Burberry"),
    ("BT-A.L", "BT Group"),
    ("CCH.L", "Coca-Cola HBC"),
    ("CNA.L", "Centrica"),
    ("CPG.L", "Compass Group"),
    ("CRDA.L", "Croda International"),
    ("CRH.L", "CRH"),
    ("CTEC.L", "ConvaTec"),
    ("DCC.L", "DCC"),
    ("DGE.L", "Diageo"),
    ("DPLM.L", "Diploma"),
    ("EDV.L", "Endeavour Mining"),
    ("ENT.L", "Entain"),
    ("EXPN.L", "Experian"),
    ("FLTR.L", "Flutter Entertainment"),
    ("FRES.L", "Fresnillo"),
    ("GLEN.L", "Glencore"),
    ("GSK.L", "GSK"),
    ("HL.L", "Hargreaves Lansdown"),
    ("HLMA.L", "Halma"),
    ("HLN.L", "Haleon"),
    ("HSBA.L", "HSBC"),
    ("HWDN.L", "Howden Joinery"),
    ("IAG.L", "IAG"),
    ("ICG.L", "ICG"),
    ("IGG.L", "IG Group"),
    ("IHG.L", "InterContinental Hotels"),
    ("III.L", "3i Group"),
    ("IMB.L", "Imperial Brands"),
    ("INF.L", "Informa"),
    ("ITRK.L", "Intertek"),
    ("JD.L", "JD Sports"),
    ("KGF.L", "Kingfisher"),
    ("LAND.L", "Land Securities"),
    ("LGEN.L", "Legal & General"),
    ("LION.L", "Lion Finance"),
    ("LLOY.L", "Lloyds Banking"),
    ("LSEG.L", "London Stock Exchange"),
    ("MKS.L", "Marks & Spencer"),
    ("MNG.L", "M&G"),
    ("MNDI.L", "Mondi"),
    ("MRO.L", "Melrose Industries"),
    ("NG.L", "National Grid"),
    ("NWG.L", "NatWest Group"),
    ("NXT.L", "Next"),
    ("PHNX.L", "Phoenix Group"),
    ("PRU.L", "Prudential"),
    ("PSH.L", "Pershing Square"),
    ("PSN.L", "Persimmon"),
    ("PSON.L", "Pearson"),
    ("REL.L", "RELX"),
    ("RIO.L", "Rio Tinto"),
    ("RKT.L", "Reckitt Benckiser"),
    ("RMV.L", "Rightmove"),
    ("RR.L", "Rolls-Royce"),
    ("RS1.L", "RS Group"),
    ("RTO.L", "Rentokil Initial"),
    ("SBRY.L", "Sainsbury's"),
    ("SDR.L", "Schroders"),
    ("SGE.L", "Sage Group"),
    ("SGRO.L", "Segro"),
    ("SHEL.L", "Shell"),
    ("SKG.L", "Smurfit Kappa"),
    ("SMDS.L", "Smith (DS)"),
    ("SMIN.L", "Smiths Group"),
    ("SMT.L", "Scottish Mortgage"),
    ("SN.L", "Smith & Nephew"),
    ("SPX.L", "Spirax-Sarco"),
    ("SSE.L", "SSE"),
    ("STAN.L", "Standard Chartered"),
    ("SVT.L", "Severn Trent"),
    ("TSCO.L", "Tesco"),
    ("TW.L", "Taylor Wimpey"),
    ("ULVR.L", "Unilever"),
    ("UTG.L", "Unite Group"),
    ("UU.L", "United Utilities"),
    ("VOD.L", "Vodafone"),
    ("WEIR.L", "Weir Group"),
    ("WPP.L", "WPP"),
    ("WTB.L", "Whitbread"),
    ("DARK.L", "Darktrace"),
    ("BBOX.L", "Tritax Big Box"),
    ("BGEO.L", "Bank of Georgia"),
    ("EVR.L", "Evraz"),
    ("POLY.L", "Polymetal"),
];

// ============================================================================
// S&P 500 (503 tickers from 500 companies, as of early 2026)
// ============================================================================

const SP500: [(&str, &str); 506] = [
    ("A", "Agilent Technologies"),
    ("AAPL", "Apple"),
    ("ABBV", "AbbVie"),
    ("ABNB", "Airbnb"),
    ("ABT", "Abbott Laboratories"),
    ("ACGL", "Arch Capital Group"),
    ("ACN", "Accenture"),
    ("ADBE", "Adobe"),
    ("ADI", "Analog Devices"),
    ("ADM", "Archer Daniels Midland"),
    ("ADP", "ADP"),
    ("ADSK", "Autodesk"),
    ("AEE", "Ameren"),
    ("AEP", "American Electric Power"),
    ("AES", "AES Corporation"),
    ("AFL", "Aflac"),
    ("AIG", "AIG"),
    ("AIZ", "Assurant"),
    ("AJG", "Arthur J. Gallagher"),
    ("AKAM", "Akamai Technologies"),
    ("ALB", "Albemarle"),
    ("ALGN", "Align Technology"),
    ("ALL", "Allstate"),
    ("ALLE", "Allegion"),
    ("AMAT", "Applied Materials"),
    ("AMCR", "Amcor"),
    ("AMD", "AMD"),
    ("AME", "Ametek"),
    ("AMGN", "Amgen"),
    ("AMP", "Ameriprise Financial"),
    ("AMT", "American Tower"),
    ("AMZN", "Amazon"),
    ("ANET", "Arista Networks"),
    ("AON", "Aon"),
    ("AOS", "A. O. Smith"),
    ("APA", "APA Corporation"),
    ("APD", "Air Products"),
    ("APH", "Amphenol"),
    ("APO", "Apollo Global Management"),
    ("APP", "AppLovin"),
    ("APTV", "Aptiv"),
    ("ARE", "Alexandria Real Estate"),
    ("ARES", "Ares Management"),
    ("ATO", "Atmos Energy"),
    ("AVGO", "Broadcom"),
    ("AVB", "AvalonBay Communities"),
    ("AVY", "Avery Dennison"),
    ("AWK", "American Water Works"),
    ("AXP", "American Express"),
    ("AXON", "Axon Enterprise"),
    ("AZO", "AutoZone"),
    ("BA", "Boeing"),
    ("BAC", "Bank of America"),
    ("BALL", "Ball Corporation"),
    ("BAX", "Baxter International"),
    ("BDX", "Becton Dickinson"),
    ("BEN", "Franklin Resources"),
    ("BF-B", "Brown-Forman"),
    ("BG", "Bunge Global"),
    ("BIIB", "Biogen"),
    ("BK", "BNY Mellon"),
    ("BKNG", "Booking Holdings"),
    ("BKR", "Baker Hughes"),
    ("BLK", "BlackRock"),
    ("BLDR", "Builders FirstSource"),
    ("BMY", "Bristol-Myers Squibb"),
    ("BR", "Broadridge Financial"),
    ("BRK-B", "Berkshire Hathaway"),
    ("BRO", "Brown & Brown"),
    ("BSX", "Boston Scientific"),
    ("BX", "Blackstone"),
    ("BXP", "BXP"),
    ("C", "Citigroup"),
    ("CAG", "Conagra Brands"),
    ("CAH", "Cardinal Health"),
    ("CARR", "Carrier Global"),
    ("CAT", "Caterpillar"),
    ("CB", "Chubb"),
    ("CBOE", "Cboe Global Markets"),
    ("CBRE", "CBRE Group"),
    ("CCI", "Crown Castle"),
    ("CCL", "Carnival"),
    ("CDNS", "Cadence Design"),
    ("CDW", "CDW"),
    ("CE", "Celanese"),
    ("CEG", "Constellation Energy"),
    ("CF", "CF Industries"),
    ("CFG", "Citizens Financial Group"),
    ("CHD", "Church & Dwight"),
    ("CHRW", "C.H. Robinson"),
    ("CHTR", "Charter Communications"),
    ("CI", "Cigna"),
    ("CIEN", "Ciena"),
    ("CINF", "Cincinnati Financial"),
    ("CL", "Colgate-Palmolive"),
    ("CLX", "Clorox"),
    ("CMCSA", "Comcast"),
    ("CME", "CME Group"),
    ("CMG", "Chipotle Mexican Grill"),
    ("CMI", "Cummins"),
    ("CMS", "CMS Energy"),
    ("CNC", "Centene"),
    ("CNP", "CenterPoint Energy"),
    ("COF", "Capital One"),
    ("COIN", "Coinbase"),
    ("COO", "Cooper Companies"),
    ("COP", "ConocoPhillips"),
    ("COR", "Cencora"),
    ("COST", "Costco"),
    ("CPAY", "Corpay"),
    ("CPB", "Campbell's Company"),
    ("CPRT", "Copart"),
    ("CPT", "Camden Property Trust"),
    ("CRH", "CRH"),
    ("CRL", "Charles River Laboratories"),
    ("CRM", "Salesforce"),
    ("CRWD", "CrowdStrike"),
    ("CSCO", "Cisco"),
    ("CSGP", "CoStar Group"),
    ("CSX", "CSX"),
    ("CTAS", "Cintas"),
    ("CTRA", "Coterra Energy"),
    ("CTSH", "Cognizant"),
    ("CTVA", "Corteva"),
    ("CVNA", "Carvana"),
    ("CVS", "CVS Health"),
    ("CVX", "Chevron"),
    ("D", "Dominion Energy"),
    ("DAL", "Delta Air Lines"),
    ("DASH", "DoorDash"),
    ("DDOG", "Datadog"),
    ("DE", "John Deere"),
    ("DECK", "Deckers Brands"),
    ("DELL", "Dell Technologies"),
    ("DG", "Dollar General"),
    ("DGX", "Quest Diagnostics"),
    ("DHI", "D.R. Horton"),
    ("DHR", "Danaher"),
    ("DIS", "Walt Disney"),
    ("DLTR", "Dollar Tree"),
    ("DLR", "Digital Realty"),
    ("DOC", "Healthpeak Properties"),
    ("DOV", "Dover Corporation"),
    ("DOW", "Dow Inc."),
    ("DPZ", "Domino's"),
    ("DRI", "Darden Restaurants"),
    ("DTE", "DTE Energy"),
    ("DUK", "Duke Energy"),
    ("DD", "DuPont"),
    ("DVA", "DaVita"),
    ("DVN", "Devon Energy"),
    ("DXCM", "DexCom"),
    ("EA", "Electronic Arts"),
    ("EBAY", "eBay"),
    ("ECL", "Ecolab"),
    ("ED", "Consolidated Edison"),
    ("EFX", "Equifax"),
    ("EIX", "Edison International"),
    ("EL", "Estée Lauder"),
    ("ELV", "Elevance Health"),
    ("EME", "Emcor Group"),
    ("EMR", "Emerson Electric"),
    ("EOG", "EOG Resources"),
    ("EPAM", "EPAM Systems"),
    ("EQIX", "Equinix"),
    ("EQR", "Equity Residential"),
    ("EQT", "EQT Corporation"),
    ("ERIE", "Erie Indemnity"),
    ("ES", "Eversource Energy"),
    ("ESS", "Essex Property Trust"),
    ("ETN", "Eaton"),
    ("ETR", "Entergy"),
    ("EVRG", "Evergy"),
    ("EW", "Edwards Lifesciences"),
    ("EXC", "Exelon"),
    ("EXE", "Expand Energy"),
    ("EXPE", "Expedia Group"),
    ("EXPD", "Expeditors International"),
    ("EXR", "Extra Space Storage"),
    ("F", "Ford"),
    ("FANG", "Diamondback Energy"),
    ("FAST", "Fastenal"),
    ("FCNCA", "First Citizens BancShares"),
    ("FDS", "FactSet"),
    ("FDX", "FedEx"),
    ("FE", "FirstEnergy"),
    ("FFIV", "F5 Networks"),
    ("FICO", "Fair Isaac"),
    ("FIS", "Fidelity National Information"),
    ("FISV", "Fiserv"),
    ("FITB", "Fifth Third Bancorp"),
    ("FIX", "Comfort Systems USA"),
    ("FOX", "Fox Corporation B"),
    ("FOXA", "Fox Corporation A"),
    ("FRT", "Federal Realty"),
    ("FSLR", "First Solar"),
    ("FTNT", "Fortinet"),
    ("FTV", "Fortive"),
    ("GD", "General Dynamics"),
    ("GDDY", "GoDaddy"),
    ("GE", "GE Aerospace"),
    ("GEHC", "GE HealthCare"),
    ("GEN", "Gen Digital"),
    ("GEV", "GE Vernova"),
    ("GILD", "Gilead Sciences"),
    ("GIS", "General Mills"),
    ("GL", "Globe Life"),
    ("GLW", "Corning"),
    ("GM", "General Motors"),
    ("GNRC", "Generac"),
    ("GOOG", "Alphabet A"),
    ("GOOGL", "Alphabet C"),
    ("GPC", "Genuine Parts"),
    ("GPN", "Global Payments"),
    ("GRMN", "Garmin"),
    ("GS", "Goldman Sachs"),
    ("GWW", "W.W. Grainger"),
    ("HAL", "Halliburton"),
    ("HAS", "Hasbro"),
    ("HCA", "HCA Healthcare"),
    ("HD", "Home Depot"),
    ("HIG", "Hartford Financial"),
    ("HII", "Huntington Ingalls"),
    ("HLT", "Hilton Worldwide"),
    ("HOLX", "Hologic"),
    ("HON", "Honeywell"),
    ("HOOD", "Robinhood Markets"),
    ("HPE", "Hewlett Packard Enterprise"),
    ("HPQ", "HP Inc."),
    ("HRL", "Hormel Foods"),
    ("HSIC", "Henry Schein"),
    ("HST", "Host Hotels & Resorts"),
    ("HSY", "Hershey"),
    ("HUBB", "Hubbell"),
    ("HUM", "Humana"),
    ("HWM", "Howmet Aerospace"),
    ("HBAN", "Huntington Bancshares"),
    ("IBM", "IBM"),
    ("ICE", "Intercontinental Exchange"),
    ("IDXX", "IDEXX Labs"),
    ("IEX", "IDEX Corporation"),
    ("IFF", "Intl Flavors & Fragrances"),
    ("INCY", "Incyte"),
    ("INTC", "Intel"),
    ("INTU", "Intuit"),
    ("INVH", "Invitation Homes"),
    ("IP", "International Paper"),
    ("IQV", "IQVIA"),
    ("IR", "Ingersoll Rand"),
    ("IRM", "Iron Mountain"),
    ("ISRG", "Intuitive Surgical"),
    ("IT", "Gartner"),
    ("ITW", "Illinois Tool Works"),
    ("IVZ", "Invesco"),
    ("J", "Jacobs Solutions"),
    ("JBHT", "J.B. Hunt"),
    ("JBL", "Jabil"),
    ("JCI", "Johnson Controls"),
    ("JKHY", "Jack Henry & Associates"),
    ("JNJ", "Johnson & Johnson"),
    ("JPM", "JPMorgan Chase"),
    ("KDP", "Keurig Dr Pepper"),
    ("KEY", "KeyCorp"),
    ("KEYS", "Keysight Technologies"),
    ("KHC", "Kraft Heinz"),
    ("KIM", "Kimco Realty"),
    ("KKR", "KKR & Co."),
    ("KLAC", "KLA Corp"),
    ("KMB", "Kimberly-Clark"),
    ("KMI", "Kinder Morgan"),
    ("KO", "Coca-Cola"),
    ("KR", "Kroger"),
    ("KVUE", "Kenvue"),
    ("L", "Loews"),
    ("LDOS", "Leidos"),
    ("LEN", "Lennar"),
    ("LH", "Labcorp"),
    ("LHX", "L3Harris"),
    ("LII", "Lennox International"),
    ("LIN", "Linde"),
    ("LLY", "Eli Lilly"),
    ("LMT", "Lockheed Martin"),
    ("LNT", "Alliant Energy"),
    ("LOW", "Lowe's"),
    ("LRCX", "Lam Research"),
    ("LULU", "Lululemon"),
    ("LUV", "Southwest Airlines"),
    ("LVS", "Las Vegas Sands"),
    ("LW", "Lamb Weston"),
    ("LYB", "LyondellBasell"),
    ("LYV", "Live Nation"),
    ("MA", "Mastercard"),
    ("MAA", "Mid-America Apartment"),
    ("MAR", "Marriott"),
    ("MAS", "Masco"),
    ("MCD", "McDonald's"),
    ("MCHP", "Microchip Technology"),
    ("MCK", "McKesson"),
    ("MCO", "Moody's"),
    ("MDLZ", "Mondelez"),
    ("MDT", "Medtronic"),
    ("MELI", "MercadoLibre"),
    ("MET", "MetLife"),
    ("META", "Meta Platforms"),
    ("MGM", "MGM Resorts"),
    ("MKC", "McCormick"),
    ("MLM", "Martin Marietta"),
    ("MMC", "Marsh McLennan"),
    ("MMM", "3M"),
    ("MNST", "Monster Beverage"),
    ("MO", "Altria"),
    ("MOH", "Molina Healthcare"),
    ("MOS", "Mosaic"),
    ("MPC", "Marathon Petroleum"),
    ("MPWR", "Monolithic Power Systems"),
    ("MRK", "Merck & Co."),
    ("MRNA", "Moderna"),
    ("MRVL", "Marvell Technology"),
    ("MS", "Morgan Stanley"),
    ("MSCI", "MSCI"),
    ("MSFT", "Microsoft"),
    ("MSI", "Motorola Solutions"),
    ("MTB", "M&T Bank"),
    ("MTCH", "Match Group"),
    ("MTD", "Mettler Toledo"),
    ("MU", "Micron"),
    ("NCLH", "Norwegian Cruise Line"),
    ("NDAQ", "Nasdaq Inc."),
    ("NDSN", "Nordson"),
    ("NEE", "NextEra Energy"),
    ("NEM", "Newmont"),
    ("NFLX", "Netflix"),
    ("NI", "NiSource"),
    ("NKE", "Nike"),
    ("NOC", "Northrop Grumman"),
    ("NOW", "ServiceNow"),
    ("NRG", "NRG Energy"),
    ("NSC", "Norfolk Southern"),
    ("NTAP", "NetApp"),
    ("NTRS", "Northern Trust"),
    ("NUE", "Nucor"),
    ("NVDA", "NVIDIA"),
    ("NVR", "NVR"),
    ("NWSA", "News Corp A"),
    ("NWS", "News Corp B"),
    ("NXPI", "NXP Semiconductors"),
    ("O", "Realty Income"),
    ("ODFL", "Old Dominion Freight"),
    ("OKE", "Oneok"),
    ("OMC", "Omnicom Group"),
    ("ON", "ON Semiconductor"),
    ("ORCL", "Oracle"),
    ("ORLY", "O'Reilly Auto"),
    ("OTIS", "Otis Worldwide"),
    ("OXY", "Occidental Petroleum"),
    ("PANW", "Palo Alto Networks"),
    ("PAYC", "Paycom"),
    ("PAYX", "Paychex"),
    ("PCAR", "PACCAR"),
    ("PCG", "PG&E"),
    ("PDD", "PDD Holdings"),
    ("PEG", "Public Service Enterprise"),
    ("PEP", "PepsiCo"),
    ("PFE", "Pfizer"),
    ("PFG", "Principal Financial"),
    ("PG", "Procter & Gamble"),
    ("PGR", "Progressive"),
    ("PH", "Parker Hannifin"),
    ("PHM", "PulteGroup"),
    ("PKG", "Packaging Corp of America"),
    ("PLD", "Prologis"),
    ("PLTR", "Palantir"),
    ("PM", "Philip Morris"),
    ("PNC", "PNC Financial"),
    ("PNR", "Pentair"),
    ("PNW", "Pinnacle West"),
    ("PODD", "Insulet"),
    ("POOL", "Pool Corporation"),
    ("PPG", "PPG Industries"),
    ("PPL", "PPL Corporation"),
    ("PRU", "Prudential Financial"),
    ("PSA", "Public Storage"),
    ("PSKY", "Paramount Skydance"),
    ("PSX", "Phillips 66"),
    ("PTC", "PTC"),
    ("PVH", "PVH Corp"),
    ("PWR", "Quanta Services"),
    ("PYPL", "PayPal"),
    ("Q", "Qnity Electronics"),
    ("QCOM", "Qualcomm"),
    ("RCL", "Royal Caribbean"),
    ("REG", "Regency Centers"),
    ("REGN", "Regeneron"),
    ("RF", "Regions Financial"),
    ("RJF", "Raymond James"),
    ("RL", "Ralph Lauren"),
    ("RMD", "ResMed"),
    ("ROK", "Rockwell Automation"),
    ("ROL", "Rollins"),
    ("ROP", "Roper Technologies"),
    ("ROST", "Ross Stores"),
    ("RSG", "Republic Services"),
    ("RTX", "RTX Corp"),
    ("RVTY", "Revvity"),
    ("SBAC", "SBA Communications"),
    ("SBUX", "Starbucks"),
    ("SCHW", "Charles Schwab"),
    ("SHW", "Sherwin-Williams"),
    ("SJM", "J.M. Smucker"),
    ("SLB", "Schlumberger"),
    ("SMCI", "Super Micro Computer"),
    ("SNA", "Snap-on"),
    ("SNDK", "Sandisk"),
    ("SNPS", "Synopsys"),
    ("SO", "Southern Co."),
    ("SOLV", "Solventum"),
    ("SPG", "Simon Property"),
    ("SPGI", "S&P Global"),
    ("SRE", "Sempra"),
    ("STE", "Steris"),
    ("STLD", "Steel Dynamics"),
    ("STT", "State Street"),
    ("STX", "Seagate Technology"),
    ("STZ", "Constellation Brands"),
    ("SW", "Smurfit Westrock"),
    ("SWK", "Stanley Black & Decker"),
    ("SWKS", "Skyworks Solutions"),
    ("SYF", "Synchrony Financial"),
    ("SYK", "Stryker"),
    ("SYY", "Sysco"),
    ("T", "AT&T"),
    ("TAP", "Molson Coors"),
    ("TDG", "TransDigm"),
    ("TDY", "Teledyne Technologies"),
    ("TECH", "Bio-Techne"),
    ("TEL", "TE Connectivity"),
    ("TER", "Teradyne"),
    ("TFC", "Truist Financial"),
    ("TGT", "Target"),
    ("TJX", "TJX Companies"),
    ("TKO", "TKO Group Holdings"),
    ("TMO", "Thermo Fisher"),
    ("TMUS", "T-Mobile US"),
    ("TPL", "Texas Pacific Land"),
    ("TPR", "Tapestry"),
    ("TRGP", "Targa Resources"),
    ("TRMB", "Trimble"),
    ("TROW", "T. Rowe Price"),
    ("TRV", "Travelers"),
    ("TSCO", "Tractor Supply"),
    ("TSLA", "Tesla"),
    ("TSN", "Tyson Foods"),
    ("TT", "Trane Technologies"),
    ("TTD", "The Trade Desk"),
    ("TTWO", "Take-Two"),
    ("TXT", "Textron"),
    ("TXN", "Texas Instruments"),
    ("TYL", "Tyler Technologies"),
    ("UAL", "United Airlines"),
    ("UBER", "Uber"),
    ("UDR", "UDR"),
    ("UHS", "Universal Health Services"),
    ("ULTA", "Ulta Beauty"),
    ("UNH", "UnitedHealth"),
    ("UNP", "Union Pacific"),
    ("UPS", "UPS"),
    ("URI", "United Rentals"),
    ("USB", "U.S. Bancorp"),
    ("V", "Visa"),
    ("VICI", "Vici Properties"),
    ("VLO", "Valero Energy"),
    ("VLTO", "Veralto"),
    ("VMC", "Vulcan Materials"),
    ("VRSK", "Verisk Analytics"),
    ("VRSN", "Verisign"),
    ("VRTX", "Vertex Pharmaceuticals"),
    ("VST", "Vistra Corp"),
    ("VTRS", "Viatris"),
    ("VTR", "Ventas"),
    ("VZ", "Verizon"),
    ("WAB", "Wabtec"),
    ("WAT", "Waters Corporation"),
    ("WBA", "Walgreens Boots Alliance"),
    ("WBD", "Warner Bros Discovery"),
    ("WDAY", "Workday"),
    ("WDC", "Western Digital"),
    ("WEC", "WEC Energy Group"),
    ("WELL", "Welltower"),
    ("WFC", "Wells Fargo"),
    ("WM", "Waste Management"),
    ("WMB", "Williams Companies"),
    ("WMT", "Walmart"),
    ("WRB", "W.R. Berkley"),
    ("WSM", "Williams-Sonoma"),
    ("WST", "West Pharmaceutical"),
    ("WTW", "Willis Towers Watson"),
    ("WY", "Weyerhaeuser"),
    ("WYNN", "Wynn Resorts"),
    ("XEL", "Xcel Energy"),
    ("XOM", "Exxon Mobil"),
    ("XYL", "Xylem"),
    ("XYZ", "Block Inc."),
    ("YUM", "Yum! Brands"),
    ("ZBRA", "Zebra Technologies"),
    ("ZBH", "Zimmer Biomet"),
    ("ZTS", "Zoetis"),
];
