/// Predefined market index constituents for the Market Screener.
/// Ticker symbols are Yahoo Finance format.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MarketIndex {
    pub id: String,
    pub name: String,
    pub region: String,
    pub ticker_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MarketIndexTicker {
    pub symbol: String,
    pub name: String,
}

pub fn get_available_indices() -> Vec<MarketIndex> {
    vec![
        MarketIndex { id: "dax40".into(), name: "DAX 40".into(), region: "DE".into(), ticker_count: DAX40.len() },
        MarketIndex { id: "eurostoxx50".into(), name: "EURO STOXX 50".into(), region: "EU".into(), ticker_count: EUROSTOXX50.len() },
        MarketIndex { id: "smi20".into(), name: "SMI 20".into(), region: "CH".into(), ticker_count: SMI20.len() },
        MarketIndex { id: "atx20".into(), name: "ATX 20".into(), region: "AT".into(), ticker_count: ATX20.len() },
        MarketIndex { id: "sp500".into(), name: "S&P 500".into(), region: "US".into(), ticker_count: SP500.len() },
        MarketIndex { id: "nasdaq100".into(), name: "NASDAQ 100".into(), region: "US".into(), ticker_count: NASDAQ100.len() },
        MarketIndex { id: "dowjones30".into(), name: "Dow Jones 30".into(), region: "US".into(), ticker_count: DOWJONES30.len() },
        MarketIndex { id: "ftse100".into(), name: "FTSE 100".into(), region: "GB".into(), ticker_count: FTSE100.len() },
    ]
}

pub fn get_index_tickers(index_id: &str) -> Option<Vec<MarketIndexTicker>> {
    let data: &[(&str, &str)] = match index_id {
        "dax40" => &DAX40,
        "eurostoxx50" => &EUROSTOXX50,
        "smi20" => &SMI20,
        "atx20" => &ATX20,
        "sp500" => &SP500,
        "nasdaq100" => &NASDAQ100,
        "dowjones30" => &DOWJONES30,
        "ftse100" => &FTSE100,
        _ => return None,
    };
    Some(
        data.iter()
            .map(|(sym, name)| MarketIndexTicker {
                symbol: sym.to_string(),
                name: name.to_string(),
            })
            .collect(),
    )
}

// ============================================================================
// DAX 40
// ============================================================================

const DAX40: [(&str, &str); 40] = [
    ("ADS.DE", "Adidas"),
    ("AIR.DE", "Airbus"),
    ("ALV.DE", "Allianz"),
    ("BAS.DE", "BASF"),
    ("BAYN.DE", "Bayer"),
    ("BEI.DE", "Beiersdorf"),
    ("BMW.DE", "BMW"),
    ("BNR.DE", "Brenntag"),
    ("CBK.DE", "Commerzbank"),
    ("CON.DE", "Continental"),
    ("1COV.DE", "Covestro"),
    ("DTG.DE", "Daimler Truck"),
    ("DBK.DE", "Deutsche Bank"),
    ("DB1.DE", "Deutsche Börse"),
    ("DHL.DE", "Deutsche Post DHL"),
    ("DTE.DE", "Deutsche Telekom"),
    ("EOAN.DE", "E.ON"),
    ("FRE.DE", "Fresenius"),
    ("HNR1.DE", "Hannover Rück"),
    ("HEI.DE", "HeidelbergCement"),
    ("HEN3.DE", "Henkel VZ"),
    ("IFX.DE", "Infineon"),
    ("MBG.DE", "Mercedes-Benz"),
    ("MRK.DE", "Merck KGaA"),
    ("MTX.DE", "MTU Aero Engines"),
    ("MUV2.DE", "Munich Re"),
    ("P911.DE", "Porsche AG"),
    ("PAH3.DE", "Porsche SE"),
    ("QIA.DE", "QIAGEN"),
    ("RHM.DE", "Rheinmetall"),
    ("RWE.DE", "RWE"),
    ("SAP.DE", "SAP"),
    ("SRT3.DE", "Sartorius VZ"),
    ("SIE.DE", "Siemens"),
    ("ENR.DE", "Siemens Energy"),
    ("SHL.DE", "Siemens Healthineers"),
    ("SY1.DE", "Symrise"),
    ("VOW3.DE", "Volkswagen VZ"),
    ("VNA.DE", "Vonovia"),
    ("ZAL.DE", "Zalando"),
];

// ============================================================================
// EURO STOXX 50
// ============================================================================

const EUROSTOXX50: [(&str, &str); 50] = [
    ("ABI.BR", "AB InBev"),
    ("ADS.DE", "Adidas"),
    ("AD.AS", "Ahold Delhaize"),
    ("AIR.DE", "Airbus"),
    ("ALV.DE", "Allianz"),
    ("AMS.DE", "AMUNDI"),
    ("ASML.AS", "ASML"),
    ("CS.PA", "AXA"),
    ("BAS.DE", "BASF"),
    ("BAYN.DE", "Bayer"),
    ("SAN.PA", "Sanofi"),
    ("BMW.DE", "BMW"),
    ("BNP.PA", "BNP Paribas"),
    ("CRG.IR", "CRH"),
    ("BN.PA", "Danone"),
    ("DB1.DE", "Deutsche Börse"),
    ("DTE.DE", "Deutsche Telekom"),
    ("EOAN.DE", "E.ON"),
    ("EL.PA", "EssilorLuxottica"),
    ("ERF.DE", "Eurofins Scientific"),
    ("ENI.MI", "ENI"),
    ("FLTR.IR", "Flutter Entertainment"),
    ("RMS.PA", "Hermès"),
    ("IBE.MC", "Iberdrola"),
    ("ITX.MC", "Inditex"),
    ("IFX.DE", "Infineon"),
    ("INGA.AS", "ING Group"),
    ("ISP.MI", "Intesa Sanpaolo"),
    ("KER.PA", "Kering"),
    ("OR.PA", "L'Oréal"),
    ("MC.PA", "LVMH"),
    ("MBG.DE", "Mercedes-Benz"),
    ("MUV2.DE", "Munich Re"),
    ("NOKIA.HE", "Nokia"),
    ("ORA.PA", "Orange"),
    ("PRX.AS", "Prosus"),
    ("SAF.PA", "Safran"),
    ("SAN.MC", "Santander"),
    ("SAP.DE", "SAP"),
    ("SU.PA", "Schneider Electric"),
    ("SIE.DE", "Siemens"),
    ("GLE.PA", "Société Générale"),
    ("STLAM.MI", "Stellantis"),
    ("TTE.PA", "TotalEnergies"),
    ("DG.PA", "Vinci"),
    ("VIV.PA", "Vivendi"),
    ("VOW3.DE", "Volkswagen VZ"),
    ("VNA.DE", "Vonovia"),
    ("AI.PA", "Air Liquide"),
    ("DSY.PA", "Dassault Systèmes"),
];

// ============================================================================
// SMI 20
// ============================================================================

const SMI20: [(&str, &str); 20] = [
    ("ABBN.SW", "ABB"),
    ("ADEN.SW", "Adecco"),
    ("GEBN.SW", "Geberit"),
    ("GIVN.SW", "Givaudan"),
    ("HOLN.SW", "Holcim"),
    ("KNIN.SW", "Kühne+Nagel"),
    ("LONN.SW", "Lonza"),
    ("NESN.SW", "Nestlé"),
    ("NOVN.SW", "Novartis"),
    ("PGHN.SW", "Partners Group"),
    ("ROG.SW", "Roche"),
    ("SREN.SW", "Swiss Re"),
    ("SCMN.SW", "Swisscom"),
    ("SLHN.SW", "Swiss Life"),
    ("SIKA.SW", "Sika"),
    ("UBSG.SW", "UBS"),
    ("ZURN.SW", "Zurich Insurance"),
    ("SGSN.SW", "SGS"),
    ("LOGN.SW", "Logitech"),
    ("SOON.SW", "Sonova"),
];

// ============================================================================
// ATX 20
// ============================================================================

const ATX20: [(&str, &str); 20] = [
    ("ANDR.VI", "Andritz"),
    ("ATS.VI", "AT&S"),
    ("BG.VI", "BAWAG Group"),
    ("CAI.VI", "CA Immo"),
    ("DO.VI", "DO & CO"),
    ("EBS.VI", "Erste Group"),
    ("EVN.VI", "EVN"),
    ("IIA.VI", "Immofinanz"),
    ("LNZ.VI", "Lenzing"),
    ("MARE.VI", "Mayr-Melnhof"),
    ("OMV.VI", "OMV"),
    ("POST.VI", "Österreichische Post"),
    ("RBI.VI", "Raiffeisen Bank Int."),
    ("SBO.VI", "Schoeller-Bleckmann"),
    ("SPI.VI", "Semperit"),
    ("TKA.VI", "Telekom Austria"),
    ("UQA.VI", "UNIQA Insurance"),
    ("VER.VI", "Verbund"),
    ("VIG.VI", "Vienna Insurance"),
    ("VOE.VI", "voestalpine"),
];

// ============================================================================
// Dow Jones 30
// ============================================================================

const DOWJONES30: [(&str, &str); 30] = [
    ("AMGN", "Amgen"),
    ("AMZN", "Amazon"),
    ("AXP", "American Express"),
    ("BA", "Boeing"),
    ("CAT", "Caterpillar"),
    ("CRM", "Salesforce"),
    ("CSCO", "Cisco"),
    ("CVX", "Chevron"),
    ("DIS", "Walt Disney"),
    ("DOW", "Dow Inc."),
    ("GS", "Goldman Sachs"),
    ("HD", "Home Depot"),
    ("HON", "Honeywell"),
    ("IBM", "IBM"),
    ("JNJ", "Johnson & Johnson"),
    ("JPM", "JPMorgan Chase"),
    ("KO", "Coca-Cola"),
    ("MCD", "McDonald's"),
    ("MMM", "3M"),
    ("MRK", "Merck & Co."),
    ("MSFT", "Microsoft"),
    ("NKE", "Nike"),
    ("NVDA", "NVIDIA"),
    ("PG", "Procter & Gamble"),
    ("SHW", "Sherwin-Williams"),
    ("TRV", "Travelers"),
    ("UNH", "UnitedHealth"),
    ("V", "Visa"),
    ("VZ", "Verizon"),
    ("WMT", "Walmart"),
];

// ============================================================================
// NASDAQ 100
// ============================================================================

const NASDAQ100: [(&str, &str); 100] = [
    ("AAPL", "Apple"),
    ("ABNB", "Airbnb"),
    ("ADBE", "Adobe"),
    ("ADI", "Analog Devices"),
    ("ADP", "ADP"),
    ("ADSK", "Autodesk"),
    ("AEP", "American Electric Power"),
    ("AMAT", "Applied Materials"),
    ("AMD", "AMD"),
    ("AMGN", "Amgen"),
    ("AMZN", "Amazon"),
    ("ANSS", "ANSYS"),
    ("APP", "AppLovin"),
    ("ARM", "Arm Holdings"),
    ("ASML", "ASML"),
    ("AVGO", "Broadcom"),
    ("AZN", "AstraZeneca"),
    ("BIIB", "Biogen"),
    ("BKNG", "Booking Holdings"),
    ("BKR", "Baker Hughes"),
    ("CCEP", "Coca-Cola Europacific"),
    ("CDNS", "Cadence Design"),
    ("CDW", "CDW"),
    ("CEG", "Constellation Energy"),
    ("CHTR", "Charter Communications"),
    ("CMCSA", "Comcast"),
    ("COST", "Costco"),
    ("CPRT", "Copart"),
    ("CRWD", "CrowdStrike"),
    ("CSGP", "CoStar Group"),
    ("CSCO", "Cisco"),
    ("CTAS", "Cintas"),
    ("CTSH", "Cognizant"),
    ("DASH", "DoorDash"),
    ("DDOG", "Datadog"),
    ("DLTR", "Dollar Tree"),
    ("DXCM", "DexCom"),
    ("EA", "Electronic Arts"),
    ("EXC", "Exelon"),
    ("FANG", "Diamondback Energy"),
    ("FAST", "Fastenal"),
    ("FTNT", "Fortinet"),
    ("GEHC", "GE HealthCare"),
    ("GILD", "Gilead Sciences"),
    ("GOOG", "Alphabet A"),
    ("GOOGL", "Alphabet C"),
    ("HON", "Honeywell"),
    ("IDXX", "IDEXX Labs"),
    ("ILMN", "Illumina"),
    ("INTC", "Intel"),
    ("INTU", "Intuit"),
    ("ISRG", "Intuitive Surgical"),
    ("KDP", "Keurig Dr Pepper"),
    ("KHC", "Kraft Heinz"),
    ("KLAC", "KLA Corp"),
    ("LIN", "Linde"),
    ("LRCX", "Lam Research"),
    ("LULU", "Lululemon"),
    ("MAR", "Marriott"),
    ("MCHP", "Microchip Technology"),
    ("MDB", "MongoDB"),
    ("MDLZ", "Mondelez"),
    ("MELI", "MercadoLibre"),
    ("META", "Meta Platforms"),
    ("MNST", "Monster Beverage"),
    ("MRNA", "Moderna"),
    ("MRVL", "Marvell Technology"),
    ("MSFT", "Microsoft"),
    ("MU", "Micron"),
    ("NFLX", "Netflix"),
    ("NVDA", "NVIDIA"),
    ("NXPI", "NXP Semiconductors"),
    ("ODFL", "Old Dominion Freight"),
    ("ON", "ON Semiconductor"),
    ("ORLY", "O'Reilly Auto"),
    ("PANW", "Palo Alto Networks"),
    ("PAYX", "Paychex"),
    ("PCAR", "PACCAR"),
    ("PDD", "PDD Holdings"),
    ("PEP", "PepsiCo"),
    ("PYPL", "PayPal"),
    ("QCOM", "Qualcomm"),
    ("REGN", "Regeneron"),
    ("ROP", "Roper Technologies"),
    ("ROST", "Ross Stores"),
    ("SBUX", "Starbucks"),
    ("SNPS", "Synopsys"),
    ("SPLK", "Splunk"),
    ("TEAM", "Atlassian"),
    ("TMUS", "T-Mobile US"),
    ("TSLA", "Tesla"),
    ("TTD", "The Trade Desk"),
    ("TTWO", "Take-Two"),
    ("TXN", "Texas Instruments"),
    ("VRSK", "Verisk Analytics"),
    ("VRTX", "Vertex Pharmaceuticals"),
    ("WBD", "Warner Bros Discovery"),
    ("WDAY", "Workday"),
    ("XEL", "Xcel Energy"),
    ("ZS", "Zscaler"),
];

// ============================================================================
// FTSE 100
// ============================================================================

const FTSE100: [(&str, &str); 100] = [
    ("AAL.L", "Anglo American"),
    ("ABF.L", "Associated British Foods"),
    ("ADM.L", "Admiral Group"),
    ("AHT.L", "Ashtead Group"),
    ("ANTO.L", "Antofagasta"),
    ("AUTO.L", "Auto Trader"),
    ("AV.L", "Aviva"),
    ("AZN.L", "AstraZeneca"),
    ("BA.L", "BAE Systems"),
    ("BARC.L", "Barclays"),
    ("BDEV.L", "Barratt Developments"),
    ("BKG.L", "Berkeley Group"),
    ("BME.L", "B&M European"),
    ("BNZL.L", "Bunzl"),
    ("BP.L", "BP"),
    ("BRBY.L", "Burberry"),
    ("BT-A.L", "BT Group"),
    ("CCH.L", "Coca-Cola HBC"),
    ("CNA.L", "Centrica"),
    ("CPG.L", "Compass Group"),
    ("CRDA.L", "Croda International"),
    ("CRH.L", "CRH"),
    ("CTEC.L", "ConvaTec"),
    ("DCC.L", "DCC"),
    ("DGE.L", "Diageo"),
    ("DPLM.L", "Diploma"),
    ("EDV.L", "Endeavour Mining"),
    ("ENT.L", "Entain"),
    ("EXPN.L", "Experian"),
    ("EZJ.L", "easyJet"),
    ("FLTR.L", "Flutter Entertainment"),
    ("FRES.L", "Fresnillo"),
    ("GLEN.L", "Glencore"),
    ("GSK.L", "GSK"),
    ("HIK.L", "Hikma Pharmaceuticals"),
    ("HL.L", "Hargreaves Lansdown"),
    ("HLMA.L", "Halma"),
    ("HLN.L", "Haleon"),
    ("HSBA.L", "HSBC"),
    ("HWDN.L", "Howden Joinery"),
    ("IAG.L", "IAG"),
    ("ICG.L", "ICG"),
    ("IHG.L", "InterContinental Hotels"),
    ("III.L", "3i Group"),
    ("IMB.L", "Imperial Brands"),
    ("INF.L", "Informa"),
    ("ITRK.L", "Intertek"),
    ("JD.L", "JD Sports"),
    ("KGF.L", "Kingfisher"),
    ("LAND.L", "Land Securities"),
    ("LGEN.L", "Legal & General"),
    ("LLOY.L", "Lloyds Banking"),
    ("LSEG.L", "London Stock Exchange"),
    ("MKS.L", "Marks & Spencer"),
    ("MNG.L", "M&G"),
    ("MNDI.L", "Mondi"),
    ("MRO.L", "Melrose Industries"),
    ("NG.L", "National Grid"),
    ("NWG.L", "NatWest Group"),
    ("NXT.L", "Next"),
    ("PHNX.L", "Phoenix Group"),
    ("PRU.L", "Prudential"),
    ("PSH.L", "Pershing Square"),
    ("PSN.L", "Persimmon"),
    ("PSON.L", "Pearson"),
    ("REL.L", "RELX"),
    ("RIO.L", "Rio Tinto"),
    ("RKT.L", "Reckitt Benckiser"),
    ("RMV.L", "Rightmove"),
    ("RR.L", "Rolls-Royce"),
    ("RS1.L", "RS Group"),
    ("RTO.L", "Rentokil Initial"),
    ("SBRY.L", "Sainsbury's"),
    ("SDR.L", "Schroders"),
    ("SGE.L", "Sage Group"),
    ("SGRO.L", "Segro"),
    ("SHEL.L", "Shell"),
    ("SKG.L", "Smurfit Kappa"),
    ("SMDS.L", "Smith (DS)"),
    ("SMIN.L", "Smiths Group"),
    ("SMT.L", "Scottish Mortgage"),
    ("SN.L", "Smith & Nephew"),
    ("SPX.L", "Spirax-Sarco"),
    ("SSE.L", "SSE"),
    ("STAN.L", "Standard Chartered"),
    ("SVT.L", "Severn Trent"),
    ("TSCO.L", "Tesco"),
    ("TW.L", "Taylor Wimpey"),
    ("ULVR.L", "Unilever"),
    ("UTG.L", "Unite Group"),
    ("UU.L", "United Utilities"),
    ("VOD.L", "Vodafone"),
    ("WEIR.L", "Weir Group"),
    ("WPP.L", "WPP"),
    ("WTB.L", "Whitbread"),
    ("DARK.L", "Darktrace"),
    ("BBOX.L", "Tritax Big Box"),
    ("BGEO.L", "Bank of Georgia"),
    ("EVR.L", "Evraz"),
    ("POLY.L", "Polymetal"),
];

// ============================================================================
// S&P 500
// ============================================================================

const SP500: [(&str, &str); 205] = [
    ("AAPL", "Apple"),
    ("ABBV", "AbbVie"),
    ("ABT", "Abbott Laboratories"),
    ("ACN", "Accenture"),
    ("ADBE", "Adobe"),
    ("ADI", "Analog Devices"),
    ("ADP", "ADP"),
    ("ADSK", "Autodesk"),
    ("AEP", "American Electric Power"),
    ("AIG", "AIG"),
    ("AMAT", "Applied Materials"),
    ("AMD", "AMD"),
    ("AMGN", "Amgen"),
    ("AMZN", "Amazon"),
    ("ANET", "Arista Networks"),
    ("APD", "Air Products"),
    ("APH", "Amphenol"),
    ("AVGO", "Broadcom"),
    ("AXP", "American Express"),
    ("BA", "Boeing"),
    ("BAC", "Bank of America"),
    ("BDX", "Becton Dickinson"),
    ("BK", "BNY Mellon"),
    ("BKNG", "Booking Holdings"),
    ("BLK", "BlackRock"),
    ("BMY", "Bristol-Myers Squibb"),
    ("BSX", "Boston Scientific"),
    ("C", "Citigroup"),
    ("CAT", "Caterpillar"),
    ("CB", "Chubb"),
    ("CCI", "Crown Castle"),
    ("CDNS", "Cadence Design"),
    ("CEG", "Constellation Energy"),
    ("CHTR", "Charter Communications"),
    ("CI", "Cigna"),
    ("CL", "Colgate-Palmolive"),
    ("CMCSA", "Comcast"),
    ("CME", "CME Group"),
    ("COF", "Capital One"),
    ("COP", "ConocoPhillips"),
    ("COST", "Costco"),
    ("CRM", "Salesforce"),
    ("CSCO", "Cisco"),
    ("CTAS", "Cintas"),
    ("CTSH", "Cognizant"),
    ("CVS", "CVS Health"),
    ("CVX", "Chevron"),
    ("D", "Dominion Energy"),
    ("DE", "John Deere"),
    ("DHR", "Danaher"),
    ("DIS", "Walt Disney"),
    ("DOW", "Dow Inc."),
    ("DUK", "Duke Energy"),
    ("ECL", "Ecolab"),
    ("EL", "Estée Lauder"),
    ("EMR", "Emerson Electric"),
    ("EOG", "EOG Resources"),
    ("EQR", "Equity Residential"),
    ("ETN", "Eaton"),
    ("EW", "Edwards Lifesciences"),
    ("EXC", "Exelon"),
    ("F", "Ford"),
    ("FANG", "Diamondback Energy"),
    ("FDX", "FedEx"),
    ("FI", "Fiserv"),
    ("FISV", "Fiserv"),
    ("GD", "General Dynamics"),
    ("GE", "GE Aerospace"),
    ("GEHC", "GE HealthCare"),
    ("GILD", "Gilead Sciences"),
    ("GM", "General Motors"),
    ("GOOG", "Alphabet A"),
    ("GOOGL", "Alphabet C"),
    ("GPN", "Global Payments"),
    ("GS", "Goldman Sachs"),
    ("HCA", "HCA Healthcare"),
    ("HD", "Home Depot"),
    ("HON", "Honeywell"),
    ("HSY", "Hershey"),
    ("HUM", "Humana"),
    ("IBM", "IBM"),
    ("ICE", "Intercontinental Exchange"),
    ("INTC", "Intel"),
    ("INTU", "Intuit"),
    ("ISRG", "Intuitive Surgical"),
    ("ITW", "Illinois Tool Works"),
    ("JCI", "Johnson Controls"),
    ("JNJ", "Johnson & Johnson"),
    ("JPM", "JPMorgan Chase"),
    ("KDP", "Keurig Dr Pepper"),
    ("KHC", "Kraft Heinz"),
    ("KLAC", "KLA Corp"),
    ("KMB", "Kimberly-Clark"),
    ("KO", "Coca-Cola"),
    ("LHX", "L3Harris"),
    ("LIN", "Linde"),
    ("LLY", "Eli Lilly"),
    ("LMT", "Lockheed Martin"),
    ("LOW", "Lowe's"),
    ("LRCX", "Lam Research"),
    ("MA", "Mastercard"),
    ("MAR", "Marriott"),
    ("MCD", "McDonald's"),
    ("MCHP", "Microchip Technology"),
    ("MCK", "McKesson"),
    ("MCO", "Moody's"),
    ("MDLZ", "Mondelez"),
    ("MDT", "Medtronic"),
    ("MET", "MetLife"),
    ("META", "Meta Platforms"),
    ("MMC", "Marsh McLennan"),
    ("MMM", "3M"),
    ("MO", "Altria"),
    ("MPC", "Marathon Petroleum"),
    ("MRK", "Merck & Co."),
    ("MS", "Morgan Stanley"),
    ("MSFT", "Microsoft"),
    ("MSI", "Motorola Solutions"),
    ("MU", "Micron"),
    ("NEE", "NextEra Energy"),
    ("NFLX", "Netflix"),
    ("NOC", "Northrop Grumman"),
    ("NOW", "ServiceNow"),
    ("NSC", "Norfolk Southern"),
    ("NVDA", "NVIDIA"),
    ("NXPI", "NXP Semiconductors"),
    ("ORCL", "Oracle"),
    ("OXY", "Occidental Petroleum"),
    ("PANW", "Palo Alto Networks"),
    ("PAYX", "Paychex"),
    ("PCAR", "PACCAR"),
    ("PEP", "PepsiCo"),
    ("PFE", "Pfizer"),
    ("PG", "Procter & Gamble"),
    ("PGR", "Progressive"),
    ("PH", "Parker Hannifin"),
    ("PLTR", "Palantir"),
    ("PM", "Philip Morris"),
    ("PNC", "PNC Financial"),
    ("PSA", "Public Storage"),
    ("PSX", "Phillips 66"),
    ("PYPL", "PayPal"),
    ("QCOM", "Qualcomm"),
    ("REGN", "Regeneron"),
    ("ROP", "Roper Technologies"),
    ("ROST", "Ross Stores"),
    ("RTX", "RTX Corp"),
    ("SBUX", "Starbucks"),
    ("SCHW", "Charles Schwab"),
    ("SHW", "Sherwin-Williams"),
    ("SLB", "Schlumberger"),
    ("SNPS", "Synopsys"),
    ("SO", "Southern Co."),
    ("SPG", "Simon Property"),
    ("SPGI", "S&P Global"),
    ("SRE", "Sempra"),
    ("SYK", "Stryker"),
    ("SYY", "Sysco"),
    ("T", "AT&T"),
    ("TDG", "TransDigm"),
    ("TFC", "Truist Financial"),
    ("TGT", "Target"),
    ("TJX", "TJX Companies"),
    ("TMO", "Thermo Fisher"),
    ("TMUS", "T-Mobile US"),
    ("TRGP", "Targa Resources"),
    ("TRV", "Travelers"),
    ("TSLA", "Tesla"),
    ("TT", "Trane Technologies"),
    ("TXN", "Texas Instruments"),
    ("UNH", "UnitedHealth"),
    ("UNP", "Union Pacific"),
    ("UPS", "UPS"),
    ("URI", "United Rentals"),
    ("USB", "U.S. Bancorp"),
    ("V", "Visa"),
    ("VLO", "Valero Energy"),
    ("VRSK", "Verisk Analytics"),
    ("VRTX", "Vertex Pharmaceuticals"),
    ("VZ", "Verizon"),
    ("WBA", "Walgreens Boots Alliance"),
    ("WBD", "Warner Bros Discovery"),
    ("WDAY", "Workday"),
    ("WELL", "Welltower"),
    ("WFC", "Wells Fargo"),
    ("WM", "Waste Management"),
    ("WMT", "Walmart"),
    ("XEL", "Xcel Energy"),
    ("XOM", "Exxon Mobil"),
    ("ZTS", "Zoetis"),
    ("ABNB", "Airbnb"),
    ("CRWD", "CrowdStrike"),
    ("DDOG", "Datadog"),
    ("FTNT", "Fortinet"),
    ("MELI", "MercadoLibre"),
    ("MRVL", "Marvell Technology"),
    ("ODFL", "Old Dominion Freight"),
    ("ON", "ON Semiconductor"),
    ("ORLY", "O'Reilly Auto"),
    ("PDD", "PDD Holdings"),
    ("TTD", "The Trade Desk"),
    ("ZS", "Zscaler"),
    ("CARR", "Carrier Global"),
    ("CPRT", "Copart"),
    ("CSGP", "CoStar Group"),
];
