//! Dynamic SQL Executor for AI-generated queries
//!
//! This module provides secure execution of SQL queries generated by the AI.
//! It validates queries to ensure only SELECT statements on allowed tables
//! are executed, with automatic LIMIT enforcement and timeout protection.

use once_cell::sync::Lazy;
use regex::Regex;
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use std::collections::hash_map::DefaultHasher;
use std::collections::HashSet;
use std::hash::{Hash, Hasher};
use std::sync::Mutex;

/// Maximum number of rows to return
const MAX_ROWS: usize = 100;

/// Allowed tables for queries (only pp_* tables)
const ALLOWED_TABLES: &[&str] = &[
    "pp_security",
    "pp_txn",
    "pp_txn_unit",
    "pp_portfolio",
    "pp_account",
    "pp_price",
    "pp_latest_price",
    "pp_fifo_lot",
    "pp_fifo_consumption",
    "pp_watchlist",
    "pp_watchlist_security",
    "pp_exchange_rate",
    "pp_taxonomy",
    "pp_classification",
    "pp_classification_assignment",
    "pp_cross_entry",
    "pp_investment_plan",
    "pp_chart_drawing",
    "pp_chat_conversation",
    "pp_chat_history",
    "pp_portfolio_history",
];

/// Forbidden SQL keywords (anything that modifies data or accesses dangerous features)
const FORBIDDEN_KEYWORDS: &[&str] = &[
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE",
    "TRUNCATE", "GRANT", "REVOKE", "ATTACH", "DETACH", "VACUUM",
    "REINDEX", "PRAGMA", "REPLACE", "UPSERT",
    "LOAD_EXTENSION", "SAVEPOINT", "RELEASE",
];

/// Session-approved SQL patterns (hash of normalized SQL)
static APPROVED_SQL_PATTERNS: Lazy<Mutex<HashSet<u64>>> =
    Lazy::new(|| Mutex::new(HashSet::new()));

/// Global session approval flag: when true, ALL SQL queries are auto-approved
/// Set when user clicks "Für Sitzung erlauben" in session mode
static SESSION_GLOBALLY_APPROVED: Lazy<Mutex<bool>> =
    Lazy::new(|| Mutex::new(false));

/// SQL query extracted from AI response
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SqlQuery {
    pub sql: String,
    pub description: String,
}

/// Result of SQL execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SqlResult {
    pub columns: Vec<String>,
    pub rows: Vec<Vec<String>>,
    pub row_count: usize,
    pub truncated: bool,
}

/// SQL validation error
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SqlValidationError {
    pub message: String,
    pub suggestion: Option<String>,
}

// ============================================================================
// SQL Extraction
// ============================================================================

/// Extracts SQL queries from AI response (```sql ... ``` blocks)
pub fn extract_sql_from_response(response: &str) -> Vec<SqlQuery> {
    static RE_SQL_BLOCK: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"```sql\s*([\s\S]*?)\s*```").unwrap()
    });

    let mut queries = Vec::new();

    for caps in RE_SQL_BLOCK.captures_iter(response) {
        if let Some(sql_match) = caps.get(1) {
            let sql = sql_match.as_str().trim().to_string();
            if !sql.is_empty() {
                queries.push(SqlQuery {
                    description: generate_query_description(&sql),
                    sql,
                });
            }
        }
    }

    queries
}

/// Removes SQL blocks from response, returns cleaned text
pub fn remove_sql_blocks(response: &str) -> String {
    static RE_SQL_BLOCK: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"```sql\s*[\s\S]*?\s*```").unwrap()
    });

    RE_SQL_BLOCK.replace_all(response, "").trim().to_string()
}

// ============================================================================
// SQL Validation
// ============================================================================

/// Strips SQL comments (block /* */ and line --) to prevent validation bypass
fn strip_sql_comments(sql: &str) -> String {
    // Remove block comments /* ... */
    static RE_BLOCK_COMMENT: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"/\*[\s\S]*?\*/").unwrap()
    });
    let result = RE_BLOCK_COMMENT.replace_all(sql, " ").to_string();

    // Remove line comments -- ...
    static RE_LINE_COMMENT: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"--[^\n]*").unwrap()
    });
    RE_LINE_COMMENT.replace_all(&result, " ").to_string()
}

/// Validates SQL query for safety
/// Returns validated (and possibly modified) SQL or an error
pub fn validate_sql(sql: &str) -> Result<String, SqlValidationError> {
    // 0. Strip comments BEFORE any validation to prevent bypass
    let sql_clean = strip_sql_comments(sql);
    let sql_upper = sql_clean.to_uppercase();
    let sql_trimmed = sql_clean.trim();

    // 0b. Reject multiple statements (semicolons)
    // Allow trailing semicolon but reject embedded ones
    let sql_no_trailing = sql_trimmed.trim_end_matches(';').trim();
    if sql_no_trailing.contains(';') {
        return Err(SqlValidationError {
            message: "Mehrere SQL-Statements sind nicht erlaubt.".to_string(),
            suggestion: Some("Sende nur eine einzelne SELECT-Abfrage.".to_string()),
        });
    }

    // 1. Must start with SELECT or WITH (CTE + SELECT)
    let trimmed_upper = sql_upper.trim_start();
    if trimmed_upper.starts_with("WITH") {
        // CTE: ensure it contains a final SELECT (not INSERT/UPDATE/DELETE after the CTE)
        // Find the last top-level statement keyword after the CTE definitions
        // A valid CTE must eventually execute a SELECT
        if !trimmed_upper.contains("SELECT") {
            return Err(SqlValidationError {
                message: "WITH/CTE muss eine SELECT-Abfrage enthalten.".to_string(),
                suggestion: Some("Füge nach dem WITH-Block eine SELECT-Abfrage hinzu.".to_string()),
            });
        }
    } else if !trimmed_upper.starts_with("SELECT") {
        return Err(SqlValidationError {
            message: "Nur SELECT-Abfragen sind erlaubt.".to_string(),
            suggestion: Some("Beginne die Query mit SELECT oder WITH ... SELECT.".to_string()),
        });
    }

    // 2. Check for forbidden keywords
    for keyword in FORBIDDEN_KEYWORDS {
        // Match as whole word to avoid false positives (e.g., "UPDATED_AT" column)
        let pattern = format!(r"\b{}\b", keyword);
        if let Ok(re) = Regex::new(&pattern) {
            if re.is_match(&sql_upper) {
                return Err(SqlValidationError {
                    message: format!("{} ist nicht erlaubt.", keyword),
                    suggestion: Some("Verwende nur SELECT für Leseabfragen.".to_string()),
                });
            }
        }
    }

    // 3. Collect CTE alias names so they pass the table check
    static RE_CTE_ALIAS: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"(?i)\bWITH\s+(\w+)\s+AS\b|\b,\s*(\w+)\s+AS\s*\(").unwrap()
    });
    let cte_aliases: HashSet<String> = RE_CTE_ALIAS.captures_iter(&sql_clean)
        .filter_map(|caps| {
            caps.get(1).or(caps.get(2)).map(|m| m.as_str().to_lowercase())
        })
        .collect();

    // 4. Check for allowed tables only (operates on comment-stripped SQL)
    // Matches both unquoted identifiers and quoted identifiers ("table" or `table`)
    static RE_TABLE: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r#"(?i)\bFROM\s+(?:"([^"]+)"|`([^`]+)`|(\w+))|\bJOIN\s+(?:"([^"]+)"|`([^`]+)`|(\w+))"#).unwrap()
    });

    let mut found_any_table = false;
    for caps in RE_TABLE.captures_iter(&sql_clean) {
        let table = caps.get(1)
            .or(caps.get(2))
            .or(caps.get(3))
            .or(caps.get(4))
            .or(caps.get(5))
            .or(caps.get(6))
            .unwrap()
            .as_str()
            .to_lowercase();
        found_any_table = true;
        if cte_aliases.contains(&table) {
            continue; // CTE alias, not a real table
        }
        if !ALLOWED_TABLES.contains(&table.as_str()) {
            return Err(SqlValidationError {
                message: format!("Tabelle '{}' ist nicht erlaubt.", table),
                suggestion: Some(format!(
                    "Erlaubte Tabellen: {}",
                    ALLOWED_TABLES.join(", ")
                )),
            });
        }
    }

    // Fail-closed: if no table was detected at all, reject (may indicate obfuscation)
    if !found_any_table && !sql_upper.contains("SELECT 1") && !sql_upper.contains("SELECT DATE") && !sql_upper.contains("SELECT STRFTIME") {
        return Err(SqlValidationError {
            message: "Keine Tabelle in der Query erkannt.".to_string(),
            suggestion: Some(format!(
                "Erlaubte Tabellen: {}",
                ALLOWED_TABLES.join(", ")
            )),
        });
    }

    // 4. Add LIMIT if missing
    let mut validated_sql = sql_trimmed.to_string();
    if !sql_upper.contains("LIMIT") {
        // Remove trailing semicolon if present
        validated_sql = validated_sql.trim_end_matches(';').to_string();
        validated_sql = format!("{} LIMIT {}", validated_sql, MAX_ROWS);
    } else {
        // Enforce maximum LIMIT
        static RE_LIMIT: Lazy<Regex> = Lazy::new(|| {
            Regex::new(r"(?i)\bLIMIT\s+(\d+)").unwrap()
        });

        if let Some(caps) = RE_LIMIT.captures(&validated_sql) {
            if let Some(limit_match) = caps.get(1) {
                if let Ok(limit) = limit_match.as_str().parse::<usize>() {
                    if limit > MAX_ROWS {
                        validated_sql = RE_LIMIT
                            .replace(&validated_sql, format!("LIMIT {}", MAX_ROWS))
                            .to_string();
                    }
                }
            }
        }
    }

    Ok(validated_sql)
}

// ============================================================================
// SQL Execution
// ============================================================================

/// Executes a validated SQL query
pub fn execute_sql(conn: &Connection, sql: &str) -> Result<SqlResult, String> {
    // Validate first
    let validated_sql = validate_sql(sql).map_err(|e| e.message)?;

    log::info!("Executing SQL: {}", &validated_sql[..validated_sql.len().min(200)]);

    // Prepare statement
    let mut stmt = conn.prepare(&validated_sql)
        .map_err(|e| format!("SQL-Fehler: {}", e))?;

    // Get column names
    let columns: Vec<String> = stmt.column_names()
        .iter()
        .map(|s| s.to_string())
        .collect();

    // Execute and collect rows
    let mut rows: Vec<Vec<String>> = Vec::new();
    let mut row_iter = stmt.query([])
        .map_err(|e| format!("Query-Fehler: {}", e))?;

    while let Some(row) = row_iter.next().map_err(|e| format!("Row-Fehler: {}", e))? {
        if rows.len() >= MAX_ROWS {
            break;
        }

        let mut values: Vec<String> = Vec::new();
        for i in 0..columns.len() {
            // Try to get as different types
            let value: String = if let Ok(v) = row.get::<_, Option<i64>>(i) {
                v.map(|n| n.to_string()).unwrap_or_else(|| "NULL".to_string())
            } else if let Ok(v) = row.get::<_, Option<f64>>(i) {
                v.map(|n| format!("{:.2}", n)).unwrap_or_else(|| "NULL".to_string())
            } else if let Ok(v) = row.get::<_, Option<String>>(i) {
                v.unwrap_or_else(|| "NULL".to_string())
            } else {
                "NULL".to_string()
            };
            values.push(value);
        }
        rows.push(values);
    }

    let truncated = rows.len() >= MAX_ROWS;
    let row_count = rows.len();

    log::info!("SQL executed: {} rows returned (truncated: {})", row_count, truncated);

    Ok(SqlResult {
        columns,
        rows,
        row_count,
        truncated,
    })
}

// ============================================================================
// Result Formatting
// ============================================================================

/// Formats SQL result as Markdown table
pub fn format_as_markdown(result: &SqlResult) -> String {
    if result.rows.is_empty() {
        return "Keine Ergebnisse gefunden.".to_string();
    }

    let mut md = String::new();

    // Header
    md.push_str("| ");
    md.push_str(&result.columns.join(" | "));
    md.push_str(" |\n");

    // Separator
    md.push('|');
    for _ in &result.columns {
        md.push_str("---|");
    }
    md.push('\n');

    // Rows
    for row in &result.rows {
        md.push_str("| ");
        // Escape pipe characters in values
        let escaped: Vec<String> = row.iter()
            .map(|v| v.replace('|', "\\|"))
            .collect();
        md.push_str(&escaped.join(" | "));
        md.push_str(" |\n");
    }

    // Footer
    if result.truncated {
        md.push_str(&format!("\n*({} Ergebnisse, auf {} begrenzt)*", result.row_count, MAX_ROWS));
    } else {
        md.push_str(&format!("\n*({} Ergebnisse)*", result.row_count));
    }

    md
}

// ============================================================================
// Session Approval System
// ============================================================================

/// Checks if a similar SQL pattern has been approved for this session
pub fn is_sql_pattern_approved(sql: &str) -> bool {
    // Check global session approval first
    if SESSION_GLOBALLY_APPROVED
        .lock()
        .map(|guard| *guard)
        .unwrap_or(false)
    {
        return true;
    }
    let pattern_hash = hash_sql_pattern(sql);
    APPROVED_SQL_PATTERNS
        .lock()
        .map(|guard| guard.contains(&pattern_hash))
        .unwrap_or(false)
}

/// Approves an SQL pattern for this session and enables global session approval
pub fn approve_sql_pattern(sql: &str) {
    // Set global session approval so ALL future queries are auto-approved
    if let Ok(mut guard) = SESSION_GLOBALLY_APPROVED.lock() {
        *guard = true;
        log::info!("Global SQL session approval enabled");
    }
    let pattern_hash = hash_sql_pattern(sql);
    if let Ok(mut guard) = APPROVED_SQL_PATTERNS.lock() {
        guard.insert(pattern_hash);
        log::info!("Approved SQL pattern (hash: {})", pattern_hash);
    }
}

/// Clears all session approvals
pub fn clear_sql_approvals() {
    if let Ok(mut guard) = SESSION_GLOBALLY_APPROVED.lock() {
        *guard = false;
    }
    if let Ok(mut guard) = APPROVED_SQL_PATTERNS.lock() {
        guard.clear();
        log::info!("Cleared all SQL pattern approvals (global flag reset)");
    }
}

/// Gets the number of approved patterns
pub fn get_approved_pattern_count() -> usize {
    APPROVED_SQL_PATTERNS
        .lock()
        .map(|guard| guard.len())
        .unwrap_or(0)
}

/// Hashes SQL pattern (normalized, without specific values)
fn hash_sql_pattern(sql: &str) -> u64 {
    let normalized = normalize_sql_for_pattern(sql);
    let mut hasher = DefaultHasher::new();
    normalized.hash(&mut hasher);
    hasher.finish()
}

/// Normalizes SQL for pattern matching
/// Removes specific values but keeps structure
fn normalize_sql_for_pattern(sql: &str) -> String {
    let mut result = sql.to_uppercase();

    // Remove string literals
    static RE_STRING: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"'[^']*'").unwrap()
    });
    result = RE_STRING.replace_all(&result, "'?'").to_string();

    // Remove numbers
    static RE_NUMBER: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"\b\d+\.?\d*\b").unwrap()
    });
    result = RE_NUMBER.replace_all(&result, "?").to_string();

    // Normalize whitespace
    static RE_WHITESPACE: Lazy<Regex> = Lazy::new(|| {
        Regex::new(r"\s+").unwrap()
    });
    result = RE_WHITESPACE.replace_all(&result, " ").to_string();

    result.trim().to_string()
}

// ============================================================================
// Helper Functions
// ============================================================================

/// Generates a human-readable description for an SQL query
fn generate_query_description(sql: &str) -> String {
    let sql_lower = sql.to_lowercase();

    // Check for common patterns
    if sql_lower.contains("dividends") || sql_lower.contains("txn_type = 'dividends'") {
        return "Dividenden abfragen".to_string();
    }
    if sql_lower.contains("txn_type = 'buy'") || sql_lower.contains("txn_type in ('buy'") {
        return "Käufe anzeigen".to_string();
    }
    if sql_lower.contains("txn_type = 'sell'") || sql_lower.contains("txn_type in ('sell'") {
        return "Verkäufe anzeigen".to_string();
    }
    if sql_lower.contains("pp_fifo_lot") && sql_lower.contains("remaining_shares") {
        return "FIFO-Lots und Einstandskurse".to_string();
    }
    if sql_lower.contains("group by") && sql_lower.contains("shares") {
        return "Aktuelle Bestände (Holdings)".to_string();
    }
    if sql_lower.contains("pp_watchlist") {
        return "Watchlist-Daten".to_string();
    }
    if sql_lower.contains("pp_latest_price") || sql_lower.contains("pp_price") {
        return "Kursdaten abfragen".to_string();
    }
    if sql_lower.contains("pp_account") && !sql_lower.contains("pp_txn") {
        return "Kontoinformationen".to_string();
    }
    if sql_lower.contains("pp_portfolio") && !sql_lower.contains("pp_txn") {
        return "Portfolio-Informationen".to_string();
    }
    if sql_lower.contains("pp_security") && !sql_lower.contains("pp_txn") {
        return "Wertpapier-Informationen".to_string();
    }
    if sql_lower.contains("running") || sql_lower.contains("over (order by") {
        return "Kontostand-Verlauf".to_string();
    }

    // Generic description based on main table
    if sql_lower.contains("pp_txn") {
        return "Transaktionen abfragen".to_string();
    }

    "Datenbank-Abfrage".to_string()
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_sql_from_response() {
        let response = r#"
Hier sind deine Käufe:

```sql
SELECT date, amount FROM pp_txn WHERE txn_type = 'BUY'
```

Das war's!
"#;
        let queries = extract_sql_from_response(response);
        assert_eq!(queries.len(), 1);
        assert!(queries[0].sql.contains("SELECT"));
    }

    #[test]
    fn test_validate_sql_select_only() {
        let result = validate_sql("SELECT * FROM pp_security");
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_sql_rejects_insert() {
        let result = validate_sql("INSERT INTO pp_security VALUES (1, 'test')");
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("SELECT"));
    }

    #[test]
    fn test_validate_sql_rejects_delete() {
        let result = validate_sql("DELETE FROM pp_security");
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_sql_rejects_forbidden_table() {
        let result = validate_sql("SELECT * FROM users");
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("nicht erlaubt"));
    }

    #[test]
    fn test_validate_sql_adds_limit() {
        let result = validate_sql("SELECT * FROM pp_security").unwrap();
        assert!(result.contains("LIMIT"));
    }

    #[test]
    fn test_validate_sql_enforces_max_limit() {
        let result = validate_sql("SELECT * FROM pp_security LIMIT 1000").unwrap();
        assert!(result.contains(&format!("LIMIT {}", MAX_ROWS)));
    }

    #[test]
    fn test_normalize_sql_pattern() {
        let sql1 = "SELECT * FROM pp_txn WHERE date = '2024-01-15' LIMIT 50";
        let sql2 = "SELECT * FROM pp_txn WHERE date = '2025-06-20' LIMIT 100";

        let pattern1 = normalize_sql_for_pattern(sql1);
        let pattern2 = normalize_sql_for_pattern(sql2);

        assert_eq!(pattern1, pattern2);
    }

    #[test]
    fn test_remove_sql_blocks() {
        let response = "Hier die Daten:\n\n```sql\nSELECT * FROM pp_txn\n```\n\nFertig!";
        let cleaned = remove_sql_blocks(response);
        assert!(!cleaned.contains("```"));
        assert!(!cleaned.contains("SELECT"));
        assert!(cleaned.contains("Hier die Daten"));
        assert!(cleaned.contains("Fertig"));
    }

    #[test]
    fn test_session_approval() {
        // Use unique SQL to avoid interference from parallel tests
        // Pattern hash is deterministic, so same structure = same hash
        let unique_sql = "SELECT id, name FROM pp_security WHERE ticker LIKE '%SESS_TEST_XYZ%'";
        let unique_similar = "SELECT id, name FROM pp_security WHERE ticker LIKE '%SESS_TEST_ABC%'";

        // Approve pattern
        approve_sql_pattern(unique_sql);

        // Check it's approved (may already be from another test run, but that's ok)
        assert!(is_sql_pattern_approved(unique_sql));

        // Similar pattern (same structure, different value) should also be approved
        assert!(is_sql_pattern_approved(unique_similar));

        // Note: Don't clear at end to avoid race conditions with parallel tests
    }

    // ============================================================================
    // Additional Tests for SQL System
    // ============================================================================

    #[test]
    fn test_extract_multiple_sql_blocks() {
        let response = r#"
Hier sind zwei Abfragen:

```sql
SELECT * FROM pp_txn WHERE txn_type = 'BUY'
```

Und noch eine:

```sql
SELECT * FROM pp_txn WHERE txn_type = 'DIVIDENDS'
```
"#;
        let queries = extract_sql_from_response(response);
        assert_eq!(queries.len(), 2);
        assert!(queries[0].sql.contains("BUY"));
        assert!(queries[1].sql.contains("DIVIDENDS"));
    }

    #[test]
    fn test_validate_sql_allows_joins() {
        let sql = r#"
            SELECT t.date, s.name
            FROM pp_txn t
            JOIN pp_security s ON s.id = t.security_id
            WHERE t.txn_type = 'BUY'
        "#;
        let result = validate_sql(sql);
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_sql_allows_date_functions() {
        let sql = "SELECT * FROM pp_txn WHERE date >= date('now', '-30 days')";
        let result = validate_sql(sql);
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_sql_rejects_drop() {
        let result = validate_sql("DROP TABLE pp_security");
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_sql_rejects_update() {
        let result = validate_sql("UPDATE pp_security SET name = 'hacked'");
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_sql_rejects_pragma() {
        let result = validate_sql("PRAGMA table_info(pp_security)");
        assert!(result.is_err());
    }

    #[test]
    fn test_generate_query_description_buy() {
        let sql = "SELECT * FROM pp_txn WHERE txn_type = 'BUY'";
        let desc = generate_query_description(sql);
        assert!(desc.contains("Käufe"));
    }

    #[test]
    fn test_generate_query_description_dividends() {
        let sql = "SELECT * FROM pp_txn WHERE txn_type = 'DIVIDENDS'";
        let desc = generate_query_description(sql);
        assert!(desc.contains("Dividenden"));
    }

    #[test]
    fn test_generate_query_description_holdings() {
        let sql = "SELECT security_id, SUM(shares) as shares FROM pp_txn GROUP BY security_id";
        let desc = generate_query_description(sql);
        assert!(desc.contains("Holdings") || desc.contains("Bestände"));
    }

    #[test]
    fn test_format_markdown_empty_result() {
        let result = SqlResult {
            columns: vec!["name".to_string()],
            rows: vec![],
            row_count: 0,
            truncated: false,
        };
        let md = format_as_markdown(&result);
        assert!(md.contains("Keine Ergebnisse"));
    }

    #[test]
    fn test_format_markdown_with_data() {
        let result = SqlResult {
            columns: vec!["date".to_string(), "name".to_string()],
            rows: vec![
                vec!["2026-01-15".to_string(), "Apple".to_string()],
                vec!["2026-01-10".to_string(), "Microsoft".to_string()],
            ],
            row_count: 2,
            truncated: false,
        };
        let md = format_as_markdown(&result);
        assert!(md.contains("| date | name |"));
        assert!(md.contains("Apple"));
        assert!(md.contains("Microsoft"));
        assert!(md.contains("(2 Ergebnisse)"));
    }

    #[test]
    fn test_format_markdown_truncated() {
        let result = SqlResult {
            columns: vec!["id".to_string()],
            rows: vec![vec!["1".to_string()]],
            row_count: 100,
            truncated: true,
        };
        let md = format_as_markdown(&result);
        assert!(md.contains("begrenzt"));
    }

    #[test]
    fn test_validate_sql_allows_subquery() {
        let sql = r#"
            SELECT * FROM pp_security
            WHERE id IN (SELECT security_id FROM pp_txn WHERE txn_type = 'BUY')
        "#;
        let result = validate_sql(sql);
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_sql_allows_case_when() {
        let sql = r#"
            SELECT SUM(CASE
                WHEN txn_type IN ('BUY', 'TRANSFER_IN') THEN shares
                ELSE -shares
            END) as total
            FROM pp_txn
        "#;
        let result = validate_sql(sql);
        assert!(result.is_ok());
    }

    #[test]
    fn test_pattern_approval_different_values_same_structure() {
        // Use unique SQL patterns to avoid interference
        let sql1 = "SELECT amount FROM pp_txn WHERE date = '2024-01-15' AND currency = 'DIFF_VAL_TEST1'";
        approve_sql_pattern(sql1);

        // Same structure, different values should also be approved
        let sql2 = "SELECT amount FROM pp_txn WHERE date = '2025-06-20' AND currency = 'DIFF_VAL_TEST2'";
        assert!(is_sql_pattern_approved(sql2));
    }

    #[test]
    fn test_pattern_approval_different_structure_not_approved() {
        // Use unique SQL patterns to avoid interference
        let sql1 = "SELECT ticker FROM pp_txn WHERE txn_type = 'STRUCT_TEST_BUY'";
        approve_sql_pattern(sql1);

        // Different structure (different table) - check it's a different hash
        // Note: We can't reliably test "not approved" in parallel tests
        // because another test might have approved a similar pattern
        // Instead, verify that different structures produce different hashes
        let pattern1 = normalize_sql_for_pattern(sql1);
        let sql2 = "SELECT uuid FROM pp_security WHERE name LIKE '%STRUCT_TEST%'";
        let pattern2 = normalize_sql_for_pattern(sql2);

        // Different structures should have different normalized patterns
        assert_ne!(pattern1, pattern2);
    }

    #[test]
    fn test_validate_sql_strips_block_comments() {
        // Attempt to hide forbidden table in block comment
        let sql = "SELECT * FROM pp_security WHERE id IN (SELECT 1 FROM /* pp_security */ sqlite_master)";
        let result = validate_sql(sql);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("sqlite_master"));
    }

    #[test]
    fn test_validate_sql_strips_line_comments() {
        // Attempt to hide table after line comment
        let sql = "SELECT * FROM pp_security -- UNION SELECT * FROM sqlite_master";
        let result = validate_sql(sql);
        // Should succeed because the comment hides the forbidden part
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_sql_rejects_multiple_statements() {
        let sql = "SELECT 1 FROM pp_security; DELETE FROM pp_security";
        let result = validate_sql(sql);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("Mehrere"));
    }

    #[test]
    fn test_validate_sql_rejects_load_extension() {
        let sql = "SELECT LOAD_EXTENSION('evil.so') FROM pp_security";
        let result = validate_sql(sql);
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_sql_allows_cte_with_select() {
        let sql = "WITH cte AS (SELECT id, name FROM pp_security) SELECT * FROM cte";
        let result = validate_sql(sql);
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_sql_rejects_cte_with_forbidden_table() {
        let sql = "WITH cte AS (SELECT * FROM sqlite_master) SELECT * FROM cte";
        let result = validate_sql(sql);
        assert!(result.is_err());
        assert!(result.unwrap_err().message.contains("nicht erlaubt"));
    }

    #[test]
    fn test_validate_sql_rejects_cte_without_select() {
        let sql = "WITH cte AS (SELECT 1) DELETE FROM pp_security";
        let result = validate_sql(sql);
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_sql_allows_trailing_semicolon() {
        let sql = "SELECT * FROM pp_security;";
        let result = validate_sql(sql);
        assert!(result.is_ok());
    }
}
